query {
  search(query: "KylinChang", type: USER, first: 1) {
    nodes {
      ... on User {
        name
        login
        id
        email
        createdAt
        followers {
          totalCount
        }
      }
    }
  }
}
